spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: 123456
    druid:
      initial-size: 3
      max-active: 100
      min-idle: 5
      max-wait: 12000
      pool-prepared-statements: true
      validation-query: select 1 from dual
  redis:
    lettuce:
      pool:
        max-active: 10
        min-idle: 0
        max-idle: 5
        max-wait: 2000
    database: 1
    host: localhost
    port: 6379
logging:
  config: classpath:log4j2.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

